# use the latest ubuntu environment (20.04) available on travis
dist: focal

language: go

# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - 1.15.x

# Only clone the most recent commit.
git:
  depth: 1

script:
  - make tests

after_success:
  - bash <(curl -s https://codecov.io/bash)