version: '3'
services:
  database:
    image: postgres
    restart: always
  api:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    environment:
      - "APP_TOKEN=${APP_TOKEN}"
      - "DB_URL=${DB_URL}"
    depends_on:
      - database
    ports:
      # TODO: add balancer
      - "80:8080"
    deploy:      
      resources:
        limits:
          cpus: '0.8'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M
    restart: always      
