version: '3'
services:
  database:
    image: postgres
  api:
    build: .
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    environment:
      - "APP_TOKEN=${APP_TOKEN}"
      - "DB_URL=${DB_URL}"
    depends_on:
      - database
    ports:
      - "8080:8080"