version: '3'
services:
  api:
    build: ./api
    environment:
      - "APP_TOKEN=${APP_TOKEN}"
      - "DB_URL=${DB_URL}"
    depends_on:
      - database
    ports:
      - "8080:8080"
  database:
    image: postgres
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_DB=${DB_NAME}"