version: '3'
services:
  database:
    container_name: financesdb
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    volumes:
      - ./deployments/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
  api:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    build: .
    env_file:
      - .env
    environment:      
      - 'DB_HOST=database'
    depends_on:
      - database
    ports:
      # TODO: add balancer
      - "80:8080"
    # deploy:      
    #   resources:
    #     limits:
    #       cpus: '0.8'
    #       memory: 50M
    #     reservations:
    #       cpus: '0.1'
    #       memory: 20M
    restart: always      
