// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	rest "github.com/erickoliv/finances-api/pkg/http/rest"
	mock "github.com/stretchr/testify/mock"

	tags "github.com/erickoliv/finances-api/tags"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, pk, owner
func (_m *Repository) Delete(ctx context.Context, pk uuid.UUID, owner uuid.UUID) error {
	ret := _m.Called(ctx, pk, owner)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, pk, owner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, pk, owner
func (_m *Repository) Get(ctx context.Context, pk uuid.UUID, owner uuid.UUID) (*tags.Tag, error) {
	ret := _m.Called(ctx, pk, owner)

	var r0 *tags.Tag
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *tags.Tag); ok {
		r0 = rf(ctx, pk, owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tags.Tag)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, pk, owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Query provides a mock function with given fields: ctx, filters
func (_m *Repository) Query(ctx context.Context, filters *rest.Query) ([]tags.Tag, error) {
	ret := _m.Called(ctx, filters)

	var r0 []tags.Tag
	if rf, ok := ret.Get(0).(func(context.Context, *rest.Query) []tags.Tag); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tags.Tag)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *rest.Query) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, tag
func (_m *Repository) Save(ctx context.Context, tag *tags.Tag) error {
	ret := _m.Called(ctx, tag)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tags.Tag) error); ok {
		r0 = rf(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
